### ISSUE TITLE
build Focal Ubuntu packages for Hets

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#2065] opened 2022-06-30 07:42 UTC
wait for #2062, #2066 and then merging of #2051 first

**Comment by tillmo** [comment] 2022-07-07 07:23
now, all prerequisites are there, so you can work on this one.

**Comment by jelmd** [comment] 2022-07-07 20:24
Is it possible to get rid off all the warnings? It is pretty hard to search in a file with 4100+ lines for an error. E.g. the 180 `Defined but not used` and 116 `* is redundant` warnings.

Another question: this requires GTK3 now? GTK2 + GLADE is not supported anymore? If so, there are some errors, which need to be fixed as well - see 2nd attached file.

**Comment by tillmo** [comment] 2022-07-14 07:48
We stick with GTK2. The switch to GTK3 should be a separate issue, see #1966

**Comment by jelmd** [comment] 2022-07-14 22:30
OK, then we need https://hackage.haskell.org/package/glade . Unfortunately this cannot be build - seems to be outdated wrt. cabal:

```
SetupWrapper.hs:84:49: error:
    * Couldn't match type `Distribution.System.Platform -> String'
                     with `[Char]'
      Expected type: String
        Actual type: Distribution.System.Platform -> String
    * Probable cause: `exeExtension' is applied to too few arguments
      In the second argument of `(<.>)', namely `exeExtension'
      In the second argument of `(</>)', namely
        `"setup" <.> exeExtension'
      In the expression: setupDir </> "setup" <.> exeExtension
   |
84 |     setupProgFile    = setupDir </> "setup" <.> exeExtension
   |                                                 ^^^^^^^^^^^^

SetupWrapper.hs:87:24: error:
    * Data constructor not in scope: Version :: [Integer] -> [a0] -> t
    * Perhaps you meant one of these:
        variable `mkVersion' (imported from Distribution.Version),
        variable `version0' (imported from Distribution.Version),
        variable `noVersion' (imported from Distribution.Version)
   |
87 |     useCabalVersion  = Version [1,8] []
   |                        ^^^^^^^

SetupWrapper.hs:113:34: error:
    * Data constructor not in scope:
        PackageName :: [Char] -> PackageName
    * Perhaps you meant one of these:
        variable `packageName' (imported from Distribution.Package),
        variable `mkPackageName' (imported from Distribution.Package),
        variable `unPackageName' (imported from Distribution.Package)
    |
113 |       let cabalDep = Dependency (PackageName "Cabal")
    |                                  ^^^^^^^^^^^

SetupWrapper.hs:117:23: error:
    * Ambiguous type variable `a1' arising from a use of `display'
      prevents the constraint `(Text a1)' from being solved.
      Probable fix: use a type annotation to specify what `a1' should be.
      These potential instances exist:
        instance Text AbiTag -- Defined in `Distribution.Compiler'
        instance Text CompilerFlavor -- Defined in `Distribution.Compiler'
        instance Text CompilerId -- Defined in `Distribution.Compiler'
        ...plus 7 others
        ...plus five instances involving out-of-scope types
        (use -fprint-potential-instances to see them all)
    * In the first argument of `(++)', namely `display useCabalVersion'
      In the second argument of `(++)', namely
        `display useCabalVersion
           ++ " but no suitable version is installed."'
      In the second argument of `($)', namely
        `"The package requires Cabal library version "
           ++
             display useCabalVersion
               ++ " but no suitable version is installed."'
    |
117 |                    ++ display useCabalVersion
    |                       ^^^^^^^^^^^^^^^^^^^^^^^

SetupWrapper.hs:126:32: error:
    * Ambiguous type variable `a2' arising from a use of `=='
      prevents the constraint `(Eq a2)' from being solved.
      Probable fix: use a type annotation to specify what `a2' should be.
      These potential instances exist:
        instance Eq AbiTag -- Defined in `Distribution.Compiler'
        instance Eq CompilerFlavor -- Defined in `Distribution.Compiler'
        instance Eq CompilerId -- Defined in `Distribution.Compiler'
        ...plus 51 others
        ...plus 73 instances involving out-of-scope types
        (use -fprint-potential-instances to see them all)
    * In the expression:
        majorVersion version == majorVersion cabalVersion
      In an equation for `sameMajorVersion':
          sameMajorVersion
            = majorVersion version == majorVersion cabalVersion
      In an equation for `preference':
          preference version
            = (sameVersion, sameMajorVersion, stableVersion, latestVersion)
            where
                sameVersion = version == cabalVersion
                sameMajorVersion
                  = majorVersion version == majorVersion cabalVersion
                majorVersion = take 2 . versionBranch
                stableVersion
                  = case versionBranch version of
                      (_ : x : _) -> even x
                      _ -> False
                ....
    |
126 |             sameMajorVersion = majorVersion version == majorVersion cabalVersion
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SetupWrapper.hs:127:41: error:
    Variable not in scope: versionBranch :: a -> [a3]
    |
127 |             majorVersion     = take 2 . versionBranch
    |                                         ^^^^^^^^^^^^^

SetupWrapper.hs:128:37: error:
    Variable not in scope: versionBranch :: Version -> [Integer]
    |
128 |             stableVersion    = case versionBranch version of
    |                                     ^^^^^^^^^^^^^

SetupWrapper.hs:146:45: error:
    * Data constructor not in scope:
        PackageName :: [Char] -> PackageName
    * Perhaps you meant one of these:
        variable `packageName' (imported from Distribution.Package),
        variable `mkPackageName' (imported from Distribution.Package),
        variable `unPackageName' (imported from Distribution.Package)
    |
146 |         let cabalPkgid = PackageIdentifier (PackageName "Cabal") cabalLibVersion
    |                                             ^^^^^^^^^^^

SetupWrapper.hs:180:49: error:
    Variable not in scope: versionBranch :: Version -> [Integer]
    |
180 |             (major1:major2:minor:_) = map show (versionBranch version ++ repeat 0)
    |                                                 ^^^^^^^^^^^^^
```
Any ideas how to fix it?

**Comment by daniilsvc** [comment] 2022-07-21 05:20
Hi, @jelmd!
I'm struggling to reproduce the error. On my Ubuntu Focal Fossa when I run `STACK= make hets` Hets is build with the command:
```
ghc -optl-s -XTemplateHaskell -threaded -rtsopts -j --make    -DNOHTTP  -DUNIX -DUNI_PACKAGE -DHASKELINE     -DWARP1   -DHAXML_COMPAT -DRDFLOGIC -DCASLEXTENSIONS   -Wall -fwarn-tabs -fwarn-unrecognised-pragmas -fno-warn-orphans -fno-warn-unused-do-bind  -o hets hets.hs
```
in that case no `GTKGLADE` symbol defined so Hets uses `uni-htk` for GUI and it successfully compiles. Even if totally remove package `libghc-gtk-dev`. If I add `-DGTKGLADE` to command above, I need to install `libghc-gtk-dev` but than everything is compiled successfully without `libghc-glade-dev`.

Version of cabal - 2.4.0.1

What should I do to reproduce the error you got?

**Comment by jelmd** [comment] 2022-07-22 09:30
Well, I'm not sure about the intention of the GTK and HTK stuff. I'm just trying to build it ;-)

But I guess, with GTK you get a little bit more out of it (`GUI/GraphMenu.hs`???) and therefore the ubuntu desktop packages were always compiled with GTK enabled. Another reason could be to get rid off the Tcl/Tk dependencies, or to simply have a more modern looking UI.

However, according to Build's var.mk `-DGTKGLADE` gets append to compiler flags only, if libghc-gtk3-dev is installed (IIRC, GTK3 was the initial target). But if one has libghc-gtk3-dev installed, one has to uninstall libghc-gtk-dev, otherwise ghc stops compiling (libghc-gtk-dev provides GTK2 bindings):
```
GUI/GtkUtils.hs:77:1: error:
    Ambiguous module name `Graphics.UI.Gtk':
      it was found in multiple packages: gtk-0.15.2 gtk3-0.15.1
   |
77 | import Graphics.UI.Gtk
   | ^^^^^^^^^^^^^^^^^^^^^^
```

Anyway, I tried compiling it with libghc-gtk-dev and indeed, this works. However, it still seems to use tcl/tk and I do not see any difference between HTK and GTK version (even UI looks like Tk for both) - so no idea, what purpose the GTK code has, or whether it gets actually used.

**Comment by jelmd** [comment] 2022-07-23 04:39
@daniilsvc Can you fix the following warnings and error as well?
```
Isabelle/IsaExport.hs:10:37: warning: [-Wtabs]
    Tab character found here, and in 31 further locations.
    Please use spaces instead.
   |
10 | newtype Export = Export (List1 Thy)             deriving (Eq,Show)
   |                                     ^^^^

Isabelle/IsaExport.hs:306:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
306 |     toHType x = Defined "Export" [] []
    |             ^

Isabelle/IsaExport.hs:316:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
316 |     toHType x = Defined "Thy" [] []
    |             ^

Isabelle/IsaExport.hs:340:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
340 |     toHType x = Defined "Keyword" [] []
    |             ^

Isabelle/IsaExport.hs:358:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
358 |     toHType x = Defined "Import" [] []
    |             ^

Isabelle/IsaExport.hs:376:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
376 |     toHType x = Defined "UseFile" [] []
    |             ^

Isabelle/IsaExport.hs:394:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
394 |     toHType x = Defined "Body" [] []
    |             ^

Isabelle/IsaExport.hs:404:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
404 |     toHType x = Defined "Body" [] []
    |             ^

Isabelle/IsaExport.hs:444:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
444 |     toHType x = Defined "Locale" [] []
    |             ^

Isabelle/IsaExport.hs:464:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
464 |     toHType x = Defined "Cls" [] []
    |             ^

Isabelle/IsaExport.hs:484:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
484 |     toHType x = Defined "TypeSynonym" [] []
    |             ^

Isabelle/IsaExport.hs:507:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
507 |     toHType x = Defined "Datatypes" [] []
    |             ^

Isabelle/IsaExport.hs:517:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
517 |     toHType x = Defined "Datatype" [] []
    |             ^

Isabelle/IsaExport.hs:538:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
538 |     toHType x = Defined "Constructor" [] []
    |             ^

Isabelle/IsaExport.hs:559:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
559 |     toHType x = Defined "Domains" [] []
    |             ^

Isabelle/IsaExport.hs:569:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
569 |     toHType x = Defined "Domain" [] []
    |             ^

Isabelle/IsaExport.hs:590:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
590 |     toHType x = Defined "DomainConstructor" [] []
    |             ^

Isabelle/IsaExport.hs:610:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
610 |     toHType x = Defined "DomainConstructorArg" [] []
    |             ^

Isabelle/IsaExport.hs:631:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
631 |     toHType x = Defined "Consts" [] []
    |             ^

Isabelle/IsaExport.hs:641:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
641 |     toHType x = Defined "ConstDef" [] []
    |             ^

Isabelle/IsaExport.hs:661:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
661 |     toHType x = Defined "Axioms" [] []
    |             ^

Isabelle/IsaExport.hs:671:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
671 |     toHType x = Defined "Axiom" [] []
    |             ^

Isabelle/IsaExport.hs:691:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
691 |     toHType x = Defined "Lemma" [] []
    |             ^

Isabelle/IsaExport.hs:711:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
711 |     toHType x = Defined "Definition" [] []
    |             ^

Isabelle/IsaExport.hs:734:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
734 |     toHType x = Defined "Funs" [] []
    |             ^

Isabelle/IsaExport.hs:760:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
760 |     toHType x = Defined "Fun" [] []
    |             ^

Isabelle/IsaExport.hs:781:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
781 |     toHType x = Defined "Equation" [] []
    |             ^

Isabelle/IsaExport.hs:791:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
791 |     toHType x = Defined "Primrec" [] []
    |             ^

Isabelle/IsaExport.hs:810:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
810 |     toHType x = Defined "Fixrec" [] []
    |             ^

Isabelle/IsaExport.hs:820:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
820 |     toHType x = Defined "FixrecFun" [] []
    |             ^

Isabelle/IsaExport.hs:841:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
841 |     toHType x = Defined "FixrecEquation" [] []
    |             ^

Isabelle/IsaExport.hs:861:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
861 |     toHType x = Defined "Premises" [] []
    |             ^

Isabelle/IsaExport.hs:871:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
871 |     toHType x = Defined "Instantiation" [] []
    |             ^

Isabelle/IsaExport.hs:891:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
891 |     toHType x = Defined "Instance" [] []
    |             ^

Isabelle/IsaExport.hs:915:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
915 |     toHType x = Defined "Subclass" [] []
    |             ^

Isabelle/IsaExport.hs:936:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
936 |     toHType x = Defined "Typedef" [] []
    |             ^

Isabelle/IsaExport.hs:962:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
962 |     toHType x = Defined "Defs" [] []
    |             ^

Isabelle/IsaExport.hs:982:13: warning: [-Wunused-matches]
    Defined but not used: `x'
    |
982 |     toHType x = Defined "Def" [] []
    |             ^

Isabelle/IsaExport.hs:1006:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1006 |     toHType x = Defined "Sort" [] []
     |             ^

Isabelle/IsaExport.hs:1016:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1016 |     toHType x = Defined "Arity" [] []
     |             ^

Isabelle/IsaExport.hs:1028:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1028 |     toHType x = Defined "Vars" [] []
     |             ^

Isabelle/IsaExport.hs:1038:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1038 |     toHType x = Defined "Parent" [] []
     |             ^

Isabelle/IsaExport.hs:1056:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1056 |     toHType x = Defined "Fixes" [] []
     |             ^

Isabelle/IsaExport.hs:1066:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1066 |     toHType x = Defined "Fix" [] []
     |             ^

Isabelle/IsaExport.hs:1086:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1086 |     toHType x = Defined "Assumes" [] []
     |             ^

Isabelle/IsaExport.hs:1096:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1096 |     toHType x = Defined "Assumption" [] []
     |             ^

Isabelle/IsaExport.hs:1117:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1117 |     toHType x = Defined "Ctxt" [] []
     |             ^

Isabelle/IsaExport.hs:1127:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1127 |     toHType x = Defined "Mixfix" [] []
     |             ^

Isabelle/IsaExport.hs:1150:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1150 |     toHType x = Defined "Arg" [] []
     |             ^

Isabelle/IsaExport.hs:1168:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1168 |     toHType x = Defined "String" [] []
     |             ^

Isabelle/IsaExport.hs:1186:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1186 |     toHType x = Defined "Break" [] []
     |             ^

Isabelle/IsaExport.hs:1204:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1204 |     toHType x = Defined "Block" [] []
     |             ^

Isabelle/IsaExport.hs:1223:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1223 |     toHType x = Defined "Proof" [] []
     |             ^

Isabelle/IsaExport.hs:1233:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1233 |     toHType x = Defined "Shows" [] []
     |             ^

Isabelle/IsaExport.hs:1253:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1253 |     toHType x = Defined "Show" [] []
     |             ^

Isabelle/IsaExport.hs:1263:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1263 |     toHType x = Defined "Bound" [] []
     |             ^

Isabelle/IsaExport.hs:1281:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1281 |     toHType x = Defined "Free" [] []
     |             ^

Isabelle/IsaExport.hs:1307:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1307 |     toHType x = Defined "Var" [] []
     |             ^

Isabelle/IsaExport.hs:1335:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1335 |     toHType x = Defined "Const" [] []
     |             ^

Isabelle/IsaExport.hs:1353:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1353 |     toHType x = Defined "App" [] []
     |             ^

Isabelle/IsaExport.hs:1364:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1364 |     toHType x = Defined "Abs" [] []
     |             ^

Isabelle/IsaExport.hs:1384:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1384 |     toHType x = Defined "TVar" [] []
     |             ^

Isabelle/IsaExport.hs:1405:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1405 |     toHType x = Defined "TFree" [] []
     |             ^

Isabelle/IsaExport.hs:1424:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1424 |     toHType x = Defined "Type" [] []
     |             ^

Isabelle/IsaExport.hs:1443:13: warning: [-Wunused-matches]
    Defined but not used: `x'
     |
1443 |     toHType x = Defined "class" [] []
     |             ^

Persistence/DatabaseConnection.hs:44:3: warning: [-Woverlapping-patterns]
    Pattern match is redundant
    In a case alternative: Just "mysql" -> ...
   |
44 |   Just "mysql" -> return $ MySQL.connection dbConfig $
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

Persistence/DatabaseConnection.hs:46:3: warning: [-Woverlapping-patterns]
    Pattern match is redundant
    In a case alternative: Just "mysql" -> ...
   |
46 |   Just "mysql" -> return $ MySQL.connection dbConfig $
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

Persistence/Database.hs:80:43: error:
    * Variable not in scope: isInfixOf :: String -> String -> Bool
    * Perhaps you want to add `isInfixOf' to one of these import lists:
        `Data.List' (Persistence/Database.hs:20:1-30)
        `Data.Text' (Persistence/Database.hs:21:1-29)
   |
80 |       if isMySql dbConfig && (searchInfix `isInfixOf` message)
   |                                           ^^^^^^^^^^^
make[1]: *** [Makefile:537: hets-opt] Error 1
make: *** [Makefile:939: hets.bin] Error 2
```

**Comment by daniilsvc** [comment] 2022-07-26 00:37
`Isabelle/IsaExport.hs` is in gitignore. It is generated from `Isabelle/IsaExport.dtd` by `utils/DtdToHaskell`. Which sources are also in gitignore. I'll check it shortly but if it's possible pls continue with current version. Rest of warnings will be fixed soon.

About error: I accidently removed `isInfixOf` function from import at line 20. On my side during compilation no symbol `MYSQL` defined and everything between `#ifdef MYSQL`  hidden from ghc, so I got warning like 'not used'. My fault.

@mcodescu, don't you mind I commit into master without PR? It's just a small hunk - get back import of `isInfixOf` in file `Persistence/Database.hs` line 20.

**Comment by mcodescu** [comment] 2022-07-26 04:14
If you already committed, then it's alright, but if not, we can follow protocol: make a pull request and I'll approve it immediately.

**Comment by daniilsvc** [comment] 2022-07-26 06:59
@jelmd error above was fixed

**Comment by tillmo** [comment] 2022-09-21 15:18
I think this is done now, right?

**Closed** 2022-10-08 17:37 UTC
