### ISSUE TITLE
prefix not found

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1749] opened 2017-09-11 09:57 UTC
```
logic OWL
%prefix( : <http://X.owl#>
        Y: <http://Y.owl#> )%
ontology O
= Class: A
  Class: Y:B SubClassOf: A
end
```
Strangely enough, the error vanishes if `SubClassOf: A` is omitted.

**Comment by mcodescu** [comment] 2017-10-14 16:21
If `SubClassOf: A` is omitted, the analysis goes through, but the same error is generated after 'Show theory'.

**Comment by mcodescu** [comment] 2017-10-14 16:36
After tracing, this seems to be a duplicate of #1622. The prefix map of O is empty.

**Comment by tillmo** [comment] 2017-10-14 16:55
good, then we can close this one as duplicate.

**Comment by mcodescu** [comment] 2017-10-14 17:10
Actually this is not a duplicate. In issue #1622, the problem is that for imported ontologies the DOL prefix map is not used. But with the example there, the DOL prefixes appear correctly in the ontologies O1 and O2. I'm now trying to understand why this is not the case here, because the situation here should be similar with that one.

**Comment by mcodescu** [comment] 2017-10-14 17:57
```
logic OWL

%prefix( 
  : <http://X.owl#>
 Y: <http://Y.owl#> 
)%

ontology O = 
  Class: A
  Class: Y:B SubClassOf: A
end
```
This goes through as expected. The only difference is the empty line between the qualification and the prefix map. Is this perhaps a parsing issue?

**Comment by tillmo** [comment] 2017-10-15 10:47
Currently, I cannot reproduce the error at all. I tried with several commits, starting with the last commit before this issue was opened. Can you reproduce it? With which commit?

**Comment by mcodescu** [comment] 2017-10-15 12:13
```
mcodescu@nuance:~/repos/Hets3$ hets -g ~/repos/testSpecs/prefixNotFound.casl
Analyzing file /home/mcodescu/repos/testSpecs/prefixNotFound.casl as library prefixNotFound
logic OWL
Analyzing spec prefixNotFound?O
hets: Y: prefix not found
mcodescu@nuance:~/repos/Hets3$ hets --version
version of hets: v0.99, 1458196355
```
This is the hets that comes from Ubuntu. I can also reproduce this on the master branch of Hets (git checkout master, git pull - Already up-to-date, then calling Hets on the example you provided).

**Comment by tillmo** [comment] 2017-10-15 12:29
strange. For me, it works with both master, and my old Ubuntu version v0.99, 1471209385.

**Comment by mcodescu** [comment] 2018-04-23 10:43
I can't reproduce this on the master branch of Hets. OK to close?

**Comment by mcodescu** [comment] 2020-10-07 03:50
Can't reproduce the error.

**Closed** 2020-10-07 03:50 UTC
Labels: C:OWL, P:major, T:bug
