### ISSUE TITLE
rejecting two axioms does not work

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1583] opened 2016-03-04 16:01 UTC
For
```
logic OWL
ontology InputSpace1 =
  <http://ontohub.org/sandbox/inconsistent.omn>
  reject Ax1, Ax2
end
```
I still get both Ax1 and Ax2 (see this using the "prove" node menu, or with "hets -o xml").

**Comment by mcodescu** [comment] 2016-03-04 16:28
I have just committed a fix. This was caused by a workaround for converting from symb_items to strings that was not correct. The example above goes through as expected now.

**Closed** 2016-03-21 09:20 UTC
Labels: P:critical
