### ISSUE TITLE
Integerate Hermit as prover for OWL2

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#1955] opened 2020-10-10 22:06 UTC
see http://www.hermit-reasoner.com/

**Comment by mcodescu** [comment] 2020-10-12 07:15
Checking consistency (on Ubuntu you might have to use full path of the jar file):
```
java -jar /home/mcodescu/Software/HermiT/HermiT.jar -l /home/mcodescu/Software/HermiT/consist.owl -k
Exception in thread "main" org.semanticweb.owlapi.reasoner.InconsistentOntologyException: Inconsistent ontology
	at org.semanticweb.HermiT.Reasoner.throwInconsistentOntologyExceptionIfNecessary(Unknown Source)
	at org.semanticweb.HermiT.Reasoner.checkPreConditions(Unknown Source)
	at org.semanticweb.HermiT.Reasoner.isSatisfiable(Unknown Source)
	at org.semanticweb.HermiT.cli.CommandLine$SatisfiabilityAction.run(Unknown Source)
	at org.semanticweb.HermiT.cli.CommandLine.main(Unknown Source)

```
Proving that an ontology is entailed by the other:
```
java -jar /home/mcodescu/Software/HermiT/HermiT.jar --premise=https://ontohub.org/sandbox/premise.owl --conclusion=https://ontohub.org/sandbox/conclusion.owl -E
```

**Comment by tillmo** [comment] 2020-10-12 07:21
good. Since Hermit can prove entailment, it should have priority over Konclude #1875 and Robot #1956

**Comment by tillmo** [comment] 2020-10-23 07:30
Here some test example, save it under test_owl.dol:
```
logic OWL

ontology O =
 Class: A
 Class: B SubClassOf: A
 Class: C SubClassOf: B
then %implies
 Class: C SubClassOf: A
end
```
and save this script as test_owl.hpf:
```
use test_owl.dol
dg-all auto 
dg basic O__E1 
prover Hermit
prove-all 
```
and then in a shell call
```
hets test_owl.hpf
```

**Comment by erithacus-rubecula** [comment] 2020-10-26 15:50
I tried to run the hets test_owl.hpf but I get the error: 'no applicable prover with name "Hermit" found'.  I thought it might be the missing HERMIT_PATH but writing it into etc/environment didn't help. What am I doing wrong here?

**Comment by mcodescu** [comment] 2020-10-26 17:17
For me it worked by removing `lib/` from `hermitJar,` as the jar file is directly in the folder where Hermit is.

**Comment by erithacus-rubecula** [comment] 2020-10-26 20:32
I removed the lib/ part when we talked about it last week, so that can't be the cause.

**Comment by mcodescu** [comment] 2020-10-26 20:40
In OWL2/Logic_OWL, provers OWL2 = [pelletProver, factProver, hermitProver] and import OWL2.ProveHermit

**Comment by erithacus-rubecula** [comment] 2021-02-08 15:25
Ok, so far the disprove.dol file works fine and as expected (with both provable and not provable conjectures).
The inconsistency file however doesn't. The problem appears to be that Hets calls Hermit for it with the options that invoke the "entailment checker" instead of the consistency checker. 
It then returns the Hermit error:
"ExitFailure 1,"","Exception in thread \"main\" org.semanticweb.owlapi.reasoner.InconsistentOntologyException: Inconsistent ontology\n\tat org.semanticweb.HermiT.Reasoner.throwInconsistentOntologyExceptionIfNecessary(Unknown Source)\n\tat org.semanticweb.HermiT.Reasoner.checkPreConditions(Unknown Source)\n\tat org.semanticweb.HermiT.Reasoner.isSubClassOf(Unknown Source)\n\tat org.semanticweb.HermiT.EntailmentChecker.visit(Unknown Source)\n\tat org.semanticweb.HermiT.EntailmentChecker.visit(Unknown Source)\n\tat uk.ac.manchester.cs.owl.owlapi.OWLSubClassOfAxiomImpl.accept(OWLSubClassOfAxiomImpl.java:162)\n\tat org.semanticweb.HermiT.EntailmentChecker.entails(Unknown Source)\n\tat org.semanticweb.HermiT.cli.CommandLine$EntailsAction.run(Unknown Source)\n\tat org.semanticweb.HermiT.cli.CommandLine.main(Unknown Source)\n"" 
I don't really know what to do about that.

**Comment by erithacus-rubecula** [comment] 2021-02-08 15:33
Also to elaborate on the "Hets calling Hermit with wrong options":
The ProveHermit.hs exports consCheck which I assume would be what Hets uses to invoke consistency checking.
consCheck should then use runTimedHermit (which then assembles the Hermit command and executes it) with the option "consistency" as the first argument.
I traced the argument runTimedHermit gets called with when I use Hets with the inconsistency file which turned out to be "" (the value that the "entailment checker"/Prover runHermit sets).

**Comment by mcodescu** [comment] 2021-02-08 17:53
This is actually the typical behavior for OWL provers: if the ontology is inconsistent, they raise an error when attempting to reason over that ontology. The correct thing to do is to catch the error from within the Hets code and to give a message to the user.

I wasn't interested in checking consistency, so the flags should not change.

**Comment by mcodescu** [comment] 2021-02-09 09:17
Have you committed all your changes to the branch 1955_Hermit-Proover-Integration? Because there seems to be a problem with disproving.

With
```
logic OWL

ontology O = 
 Class: C
 Class: D SubClassOf: C
 Individual: i Types: D
then %implies
 Individual: i Types: C
```
I can call Hermit to prove the intended consequence, so there are no issues with the path. However, with 
```
logic OWL

ontology O = 
 Class: C
 Class: D
then %implies
 Class: C SubClassOf: D
```
I get an error after selecting Hermit and starting the proof "Could not find hermit reasoner. Is $HERMIT_PATH set?". The problem seems to be that in `runTimedHermit` we return success as the first component of the tuple only if the proof was successful. We should return `True` also if `outS` is False. I also had to add a case to `analyseOutput` to get the results:
```
...
["false"] ->
            (ATPSuccess, Just False, to)
...
```
With these two changes, Hets is now able to use Hermit to disprove the conjecture that C is a subclass of D, as it should.

**Comment by erithacus-rubecula** [comment] 2021-02-09 13:54
I haven't committed my changes yet, but I had the "false" part in the analyseOutput. I didn't alter anything on the output for runTimedHermit yet but haven't encountered the problem you faced with the second example.

**Comment by mcodescu** [comment] 2021-02-09 13:55
OK, then I'll test again when you commit.

**Comment by erithacus-rubecula** [comment] 2021-02-10 15:06
I've commited the changes but kept the trace parts in for now.

**Comment by mcodescu** [comment] 2021-11-03 13:53
Fixed by https://github.com/spechub/Hets/pull/2026.

**Closed by mcodescu** 2021-11-03 13:53 UTC
Labels: C:provers, P:major, C:OWL, Hiwi
