### ISSUE TITLE
NeSy signature morphisms (=refinements) should be able to map downwards the class hierarchy

### ISSUE THREAD

**Issue by tillmo** [spechub/Hets#2085] opened 2022-07-28 08:52 UTC
With
```
%prefix( ontohub: <https://ontohub.org/meta/> )% 
logic NeSyPatterns    
pattern Model = data ontohub:NeSyPatterns.omn
  Model;
pattern SemanticModel = data ontohub:NeSyPatterns.omn
  Semantic_Model; 
view v : Model to SemanticModel  
```
I get `illegal NeSyPatterns morphism` for the last line, which is a bit cryptic.
With
```
%prefix( ontohub: <https://ontohub.org/meta/> )%
logic NeSyPatterns    
pattern Model = data ontohub:NeSyPatterns.omn
  Model;
pattern SemanticModel = data ontohub:NeSyPatterns.omn
  Semantic_Model; 
view v : Model to SemanticModel =
  Model |-> Semantic_Model
```
I get
```
file:///home/till/temp/nesy.dol:8.1-10.3: *** Error:
unknown symbols '[]'
file:///home/till/temp/nesy.dol:8.1-10.3: *** Error:
unknown symbols '[]'
file:///home/till/temp/nesy.dol:8.1-10.3: *** Error:
illegal NeSyPatterns morphism
```
For the first (but not the second) example, the error vanishes if I replace `Semantic_Model` with `Model`, so I guess the condition that signature morphisms may map classes to sublcasses has not been implemented.
Moreover, the second example indicates that explicit symbol maps causes problems (which might be a separate issue).

**Comment by tillmo** [comment] 2022-07-28 10:06
This also produces an error:
```
%prefix( ontohub: <https://ontohub.org/meta/> )%                              
logic NeSyPatterns    
pattern Model = data ontohub:NeSyPatterns.omn
  Model;
end  
pattern Process = data ontohub:NeSyPatterns.omn
  Model -> Process;
end
view R : Model to Process
```

**Comment by mcodescu** [comment] 2022-09-24 10:01
In the first case, the morphism is not valid, as `Model` is mapped identically. We should improve the `induced_from_to` method.
But in the second case, the following goes through as expected on the 2095 branch:
```
%prefix( : <https://ontohub.org/meta/> )% 
logic NeSyPatterns    
pattern Model = data NeSyPatterns.omn
  Model;
end 

pattern SemanticModel = data NeSyPatterns.omn
  Semantic_Model;
end

view v : Model to SemanticModel = 
 Model |-> Semantic_Model
end
```

**Comment by mcodescu** [comment] 2022-09-24 10:03
> %prefix( ontohub: <https://ontohub.org/meta/> )%                              
> logic NeSyPatterns    
> pattern Model = data ontohub:NeSyPatterns.omn
>   Model;
> end  
> pattern Process = data ontohub:NeSyPatterns.omn
>   Model -> Process;
> end
> view R : Model to Process

This one worked by explicitly adding `Model |-> Model`.

**Comment by mcodescu** [comment] 2022-09-24 10:56
For this last example, the problem is that we get:
- mapped nodes from the source signature
```
fromList [ResolvedNode {resolvedOTerm = Model, resolvedNeSyId = gn_nesy0, resolvedNodeRange = nullRange}]
```
- nodes of the target signature
```
fromList [ResolvedNode {resolvedOTerm = Model, resolvedNeSyId = gn_nesy1, resolvedNodeRange = nullRange},ResolvedNode {resolvedOTerm = Process, resolvedNeSyId = gn_nesy0, resolvedNodeRange = nullRange}]
```

I think the method `makePMapR` should ensure that a ResolvedNode is mapped to the ResolvedNode with the same resolvedOTerm, or, if possible, we should take care to generate the same id for the same resolvedOTerm. @b-gehrke what do you think?

**Comment by tillmo** [comment] 2022-09-28 07:54
yes, the example works for me, too. But this one does not:
```
%prefix( : <https://ontohub.org/meta/> )%

logic NeSyPatterns    
pattern Model = data NeSyPatterns.omn
  Model;
end
pattern Train = data NeSyPatterns.omn
  Symbol -> Training -> Model;
end
pattern SemanticDeduction = data NeSyPatterns.omn
  Symbol -> d : Deduction -> Symbol;
  Semantic_Model -> d : Deduction; 
end
view R1 : Model to Train =
  Model |-> Model
end
view R2 : Model to SemanticDeduction =
  Model |-> Semantic_Model
end
network N =
  Train, SemanticDeduction, R1, R2
end
pattern SemanticGenerateAndTrain =
  combine N
end
```
I get:
```
file:///home/till/till/trunk/NeSy-patterns/nesyExample.dol:17.1-19.3:
*** Error:
unknown symbols '[gn_nesy2 : Model]'
file:///home/till/till/trunk/NeSy-patterns/nesyExample.dol:17.1-19.3:
*** Error:
illegal NeSyPatterns morphism
```

**Comment by mcodescu** [comment] 2022-09-28 11:42
I have added a more detailed error message:
```
Incompatible mapping:
fromList [ResolvedNode {resolvedOTerm = Semantic_Model, resolvedNeSyId = gn_nesy2, resolvedNodeRange = nullRange}] 
and 
fromList [ResolvedNode {resolvedOTerm = Deduction, resolvedNeSyId = d, resolvedNodeRange = nullRange},ResolvedNode {resolvedOTerm = Semantic_Model, resolvedNeSyId = gn_nesy0, resolvedNodeRange = nullRange},ResolvedNode {resolvedOTerm = Symbol, resolvedNeSyId = gn_nesy1, resolvedNodeRange = nullRange},ResolvedNode {resolvedOTerm = Symbol, resolvedNeSyId = gn_nesy2, resolvedNodeRange = nullRange}]
```
The problem is that `(gn_nesy0, Model)` is mapped to `(gn_nesy2, Semantic_Model)`, while the target signature contains `(gn_nesy0, Semantic_Model)`. I don't understand why `gn_nesy2` is assigned to `Semantic_model`, there seems to be a problem with the method `Analysis.resolveNode`, as in `Analysis.symbToSymbol` I get `resolved = Result {diags = [*** Error: Cannot uniquely resolve unset nesyid. 'Semantic_Model'], maybeResult = Nothing}`. @b-gehrke could you help figure out what is going on?

**Comment by mcodescu** [comment] 2022-09-28 11:57
It seems to me that we try to resolve `Node {ontologyTerm = Semantic_Model, nesyId = Nothing, nodeRange = nullRange}` as an id, when it is actually an OWL class.

**Comment by b-gehrke** [comment] 2022-09-28 15:51
Indeed, there is something wrong with either `resolveNode` or `findId`. I'm looking into this. 
A quickfix seems to assign ids

```
%prefix( : <https://ontohub.org/meta/> )%

logic NeSyPatterns    
pattern Model = data NeSyPatterns.omn
  Model;
end
pattern Train = data NeSyPatterns.omn
  Symbol -> Training -> Model;
end
pattern SemanticDeduction = data NeSyPatterns.omn
  Symbol -> d : Deduction -> Symbol;
  sm : Semantic_Model -> d : Deduction; 
end
view R1 : Model to Train =
  Model |-> Model
end
view R2 : Model to SemanticDeduction =
  Model |-> sm : Semantic_Model
end
network N =
  Train, SemanticDeduction, R1, R2
end
pattern SemanticGenerateAndTrain =
  combine N
end
```

**Comment by b-gehrke** [comment] 2022-09-28 17:09
The issue is fixed in the linked branch 2085-nesy-signature-morphisms-=refinements-should-be-able-to-map-downwards-the-class-hierarchy. However, without explicit ids I know get
```
file:///home/bjoern/development/Hets/test.dol:24.3: *** Error:
couldn't compute greatest lower bound
```

Again, specifying the ids explicitly resolves the issue.

**Comment by mcodescu** [comment] 2022-09-28 17:10
This is a problem in the colimit computation, I'll have a look.

**Comment by mcodescu** [comment] 2022-09-28 18:31
@tillmo is the colimit correct, with ids specified explicitly? We get
```
d : Deduction -> gn_nesy0 : Symbol;
gn_nesy0 : Semantic_Model -> d : Deduction;
gn_nesy2 : Symbol -> gn_nesy1 : Training;
gn_nesy0 : Symbol -> d : Deduction;
gn_nesy1 : Training -> gn_nesy0 : Semantic_Model;
```
and while Model and Semantic_Model are identified because they have a common source in the diagram, we have two labels for the id `gn_nesy0` and this should not be allowed.

**Comment by tillmo** [comment] 2022-09-28 21:21
Right, each id should be labled by only one ontology term. Moreover, `gn_nesy0 : Symbol` appears twice, but these should have different ids (and actually, in `SemanticDeduction`, they have different ids).

**Comment by mcodescu** [comment] 2022-09-28 21:25
There's a problem with making two IRIs with no common origin in the diagram distinct. I asked Björn to help.

**Comment by mcodescu** [comment] 2022-09-29 06:09
After correcting how suffixes are added to IRIs in the colimit, I now get:
```
d : Deduction -> gn_nesy04 : Symbol;
gn_nesy02 : Semantic_Model -> d : Deduction;
gn_nesy14 : Symbol -> d : Deduction;
gn_nesy2 : Symbol -> gn_nesy13 : Training;
gn_nesy13 : Training -> gn_nesy02 : Semantic_Model;
```
@tillmo please check that it is right.

**Comment by tillmo** [comment] 2022-09-29 06:20
thanks, looks good!

**Comment by tillmo** [comment] 2022-09-29 06:43
could you please file a pull request for `2085-nesy-signature-morphisms-=refinements-should-be-able-to-map-downwards-the-class-hierarchy`?

**Comment by mcodescu** [comment] 2022-09-29 06:45
Just did, but we shouldn't close the issue, there are still problems with computing the colimit when we don't use explicit ids, I'm looking at that now.

**Comment by mcodescu** [comment] 2022-09-29 06:50
No, we don't need the explicit ids, we can remove `sm :` before `SemanticModel` and the example goes through.

**Closed** 2022-09-29 07:28 UTC
