### ISSUE TITLE
How to translate CASL into TPTP File?

### ISSUE THREAD

**Issue by gibso** [spechub/Hets#1905] opened 2019-07-18 14:29 UTC
How can i translate CASL files into TPTP files? 
As casl input file i am using the minimal example file from hets. The content is the following:
```
spec Strict_Partial_Order =
sort Elem
pred __<__ : Elem * Elem
forall x, y, z:Elem
. not x < x %(irreflexive)%
. x < y /\ y < z => x < z %(transitive)%
%% the following is logically entailed
. x < y => not y < x %(asymmetric)% %implied
end
```

now I am using the following command:
```
hets -o tptp example.casl
```

that gives me the following output:
```
Analyzing file file:///data/casl/example.casl as library example
Analyzing spec Strict_Partial_Order
expected RDF theory for: ./example_Strict_Partial_Order.tptp
```
the exit code of that command is 0, but there is no tptp file. How can i provide a RDF theory for the file? Or is this a bug?

Thanks for your significant work everyone.

**Comment by tillmo** [comment] 2019-07-18 14:36
The message `expected RDF theory for ...` is indeed a bug.

A workaround: it works if you explicitly select the logic translation (the `v2` option is just for logging the output file name): 
```
hets -o tptp -t CASL2TPTP_FOF -v2 example.casl
```

**Comment by gibso** [comment] 2019-07-18 16:03
Hello @tillmo,

thank you for your fast reply.

When i add the translation explicitly the minimal example is successfully converted into a tptp file.
But when i use more complex files, like the *[Examples/List.casl](https://github.com/spechub/Hets-lib/blob/master/Examples/List.casl)* File from the [Hets-lib](https://github.com/spechub/Hets-lib) repository, the bug (partly) occurs again.
I execute
```
hets -o tptp -t CASL2TPTP_FOF -v2 List.casl
```
and get the output:
```
Reading file file:///data/hets-lib/Examples/List.casl
Analyzing library Examples/List
Analyzing spec Elem
Analyzing spec List
Analyzing spec Monoid
Analyzing view MonoidAsList
Analyzing spec Nat
Analyzing spec NatList
Translated using comorphism CASL2TPTP_FOF : CASL -> TPTP
Writing file: ./List_Elem.tptp
### Warning:
for 'CASL2TPTP_FOF' expected sublogic 'SulFOL=E'
 but found sublogic 'eCPrenex=' with signature sublogic 'Atom'
Keeping untranslated theory
expected RDF theory for: ./List_List.tptp
Translated using comorphism CASL2TPTP_FOF : CASL -> TPTP
Writing file: ./List_Monoid.tptp
### Warning:
for 'CASL2TPTP_FOF' expected sublogic 'SulFOL=E'
 but found sublogic 'eCPrenexAlg=' with signature sublogic 'Eq'
Keeping untranslated theory
expected RDF theory for: ./List_Nat.tptp
### Warning:
for 'CASL2TPTP_FOF' expected sublogic 'SulFOL=E'
 but found sublogic 'eCPrenex=' with signature sublogic 'Atom'
Keeping untranslated theory
expected RDF theory for: ./List_NatList.tptp
### Warning:
for 'CASL2TPTP_FOF' expected sublogic 'SulFOL=E'
 but found sublogic 'eCPrenex=' with signature sublogic 'Atom'
Keeping untranslated theory
expected RDF theory for: ./List_gn_n1.tptp
Translated using comorphism CASL2TPTP_FOF : CASL -> TPTP
Writing file: ./List_gn_n4.tptp
### Warning:
for 'CASL2TPTP_FOF' expected sublogic 'SulFOL=E'
 but found sublogic 'eCPrenex=' with signature sublogic 'Atom'
Keeping untranslated theory
expected RDF theory for: ./List_gn_n5.tptp
```

The three files `List_Elem.tptp`, `List_Monoid.tptp` and `List_gn_n4.tptp` have been successfully created, but for the rest of the nodes there occurs the RDF message and no file is created.

When I execute the command without explic transformation, no file is created, so this is imroving something. Apparently it is the *"eCPrenex sublogic"* that causes the problem. Maybe there is another parameter that can explicitly name the sublogic?

Thank you,
Oliver.

**Comment by gibso** [comment] 2019-07-19 12:32
For some further research i built the master branch of hets and executed the command with that hets binary. I get the following output for a failing node transformation:
```
...
### Warning:
SuleCFOL2TPTP: Sort generation axioms are not yet supported.
Keeping untranslated theory
expected RDF theory for: ../Hets-lib/Examples/List_Nat.tptp
...
```
In the codebase of hets this Exception is commented with a reference to #1706. So it is obviously not supported to transform generation axioms. Is it possible to transform a CASL File into a Syntax without generation axioms?

**Comment by tillmo** [comment] 2019-07-20 13:30
I have corrected the error message in #1906 into "expected TPTP theory for..." - then it makes more sense.

Indeed, the problem is that sort generation constraints (a form of second-order induction axioms) cannot be translated to TPTP. #1706 proposes to solve this problem in case of a TPTP proof. But here, we just want to apply a translation (institution comorphism) from CASL to TPTP. We need to restrict the CASL theory to a sublogic without sort generation constraints. Possible ways are:
1.  using an institution morphism. However, currently, institution morphisms have not been fully implemented yet
1.  to add a "permissive" flag to institution comorphisms that signals that untranslatable sentences shall be omitted
1. to use a projection to a sublogic

**Comment by tillmo** [comment] 2019-07-21 10:21
OK, #1907 (branch `1905_lossy_translation`) implements the second option, a lossy flag. Call Hets with `-Y`. Note that this branch should not be merged into master before #1706 is solved. So for now, you have to work with the branch `1905_lossy_translation`. If you need a binary for that branch, please tell me.

**Comment by gibso** [comment] 2019-07-21 10:26
thats fantastic, thank you so much!

**Comment by tillmo** [comment] 2019-07-23 17:47
OK, in the meantime, I managed circumvent the #1706 problem, and merged this into `master`. So the issue is fixed.

**Closed by tillmo** 2019-07-23 17:47 UTC
Labels: P:major, T:bug
