### ISSUE TITLE
TPTP/THF: No Symbols in Axioms/Theorems

### ISSUE THREAD

**Issue by eugenk** [spechub/Hets#1546] opened 2015-11-26 08:35 UTC
Hets does not output any Symbols in the Axioms and Theorems for TPTP and THF:

##### TPTP (bad output)
```
$ hets -o xml --full-signatures -a none -v2 -O /tmp/ +RTS -K1G -RTS --full-theories -A https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/compts_1__t10_compts_1.p --input-type=tptp
$ cat /tmp/compts_1__t10_compts_1.p.xml
<?xml version='1.0' ?>
<DGraph filename="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/compts_1__t10_compts_1.p" mime-type="text/plain" libname="compts_1__t10_compts_1" dgnodes="1" dgedges="0" nextlinkid="0">
  <DGNode name="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/compts_1__t10_compts_1.p" reference="false" logic="SoftFOL" refname="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/compts_1__t10_compts_1.p" relxpath="/">
    <Declarations>
      <Symbol kind="sort" name="U" iri="U">U</Symbol>
      [...]
      <Symbol kind="predicate" name="v2_compts_1" iri="v2_compts_1">v2_compts_1: U * U</Symbol>
    </Declarations>
    <Symbols>
      <Symbol kind="sort" name="U" iri="U">U</Symbol>
      [...]
      <Symbol kind="predicate" name="v2_compts_1" iri="v2_compts_1">v2_compts_1: U * U</Symbol>
    </Symbols>
    <Axioms>
      <Axiom name="antisymmetry_r2_hidden">
        <Text>[...]</Text>
        <AST>[...]</AST>
### Symbols should be here ###
      </Axiom>
      [...]
    </Axioms>
    <Theorems>
      <Theorem status="open" name="t10_compts_1">
        <Text>[...]</Text>
        <AST>[...]</AST>
### Symbols should be here ###
      </Theorem>
    </Theorems>
  </DGNode>
</DGraph>
```

##### THF (bad output)
```
$ hets -o xml --full-signatures -a none -v2 -O /tmp/ +RTS -K1G -RTS --full-theories -A https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/ALG294-5.het
$ cat /tmp/ALG294-5.xml
<?xml version='1.0' ?>
<DGraph filename="https://gist.githubusercontent.com/eugenk/1e4dcbc0106e5120bb06/raw/8f9ea2860eee9006940ae17bc42c63781c8edc69/ALG294-5.het" mime-type="text/het" libname="ALG2945" dgnodes="1" dgedges="0" nextlinkid="0">
  <DGNode name="ALG2945" range="https://gist.githubusercontent.com/eugenk/1e4dcbc0106e5120bb06/raw/8f9ea2860eee9006940ae17bc42c63781c8edc69/ALG294-5.het:3.1-3.14" reference="false" logic="THF" refname="ALG2945" relxpath="/">
    <Theorems>
      <Theorem status="open" name="cPU_X2310B_pme" range="https://gist.githubusercontent.com/eugenk/1e4dcbc0106e5120bb06/raw/8f9ea2860eee9006940ae17bc42c63781c8edc69/ALG294-5.het:58.13-192.22">
        <Text>[...]</Text>
        <AST>[...]</AST>
### Symbols should be here ###
      </Theorem>
    </Theorems>
  </DGNode>
</DGraph>
```

##### CASL (good output)
```
$ hets -o xml --full-signatures -a none -v2 -O /tmp/ +RTS -K1G -RTS --full-theories -A https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl
$ cat /tmp/Subclass.xml
<?xml version='1.0' ?>
<DGraph filename="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl" mime-type="text/het" libname="Subclass" dgnodes="3" dgedges="2" nextlinkid="2">
  <DGNode name="Subclass" range="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl:1.1-19.3" reference="false" logic="CASL" refname="Subclass" relxpath="/">
    <Declarations>
      <Symbol kind="sort" name="s" iri="s" range="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl:2.8">sort s</Symbol>
      [...]
    </Declarations>
    <Symbols>
      <Symbol kind="sort" name="s" iri="s" range="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl:2.8">sort s</Symbol>
      [...]
    </Symbols>
    <Axioms>
      <Axiom name="transitivity" range="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl:11.20-13.72">
        <Text>[...]</Text>
### Symbols are here: ###
        <Symbol kind="sort" name="s" iri="s" range="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl:13.18">sort s</Symbol>
        <Symbol kind="pred" name="subclass" iri="subclass" range="https://gist.github.com/eugenk/95b5c14c29f761dac07e/raw/a7ced0926bb6f1b4b0efc6277bbcfba57a680fba/Subclass.casl:13.22-13.29">pred subclass : s * s</Symbol>
        <AST>[...]</AST>
      </Axiom>
      [...]
    </Axioms>
  </DGNode>
  [...]
</DGraph>
```

**Comment by tillmo** [comment] 2015-11-26 08:49
@sternk, this is extremely urgent for @eugenk's master's thesis. Could you have a quick look?

**Comment by tillmo** [comment] 2015-11-26 10:30
@cmaeder, is this easy to fix? I have seen that you already have fixed #1510, which is related.

**Comment by sternk** [comment] 2015-11-26 10:43
I dont yet know where to start but I'll try

**Comment by cmaeder** [comment] 2015-11-26 10:49
I guess `symsOfSen` needs to be implemented properly. (and `sym_of`)

**Comment by sternk** [comment] 2015-11-26 10:49
Ok. Thanks for the hint!

**Comment by tillmo** [comment] 2015-11-26 11:00
sym_of has already been implemented, see function symOf in SoftFOL.Morphism. For symsOfSen, you just have to recursively go through the sentence and collect all its symbols.

**Comment by sternk** [comment] 2015-11-26 11:05
True, but that's the wrong logic. This is relevant to THF

**Comment by eugenk** [comment] 2015-11-26 11:14
It's wrong for both, SoftFOL and THF.

**Comment by sternk** [comment] 2015-11-26 11:15
I was just saying that Till's hint does not apply to this ticket.

**Comment by tillmo** [comment] 2015-11-26 11:15
but @eugenk's example is in SoftFOL. @eugenk, do you need this feature for THF, for SoftFOL, or for both?

**Comment by eugenk** [comment] 2015-11-26 11:16
I need it for both, but SoftFOL is a tad more urgent.

**Comment by tillmo** [comment] 2015-11-26 11:17
OK, then I will implement it for SoftFOL, and @sternk, could you please implement it for THF?

**Comment by sternk** [comment] 2015-11-26 11:18
Yes. Already working on it.

**Comment by sternk** [comment] 2015-11-26 11:37
1286c8879e65ab8cd9c1c9d2415652dd0f6f41cd should fix this for THF - @eugenk can you please have a look?

**Comment by eugenk** [comment] 2015-11-26 11:45
There are still no Symbols for the given file. Maybe this is a combination of #1545 (there are no Axioms) and that the theorems/conjectures are ignored when collecting the symbols. I'm not sure, though.

**Comment by sternk** [comment] 2015-11-26 11:46
Since I worked on THF (not SoftFOL) you'd have to test with one of the
files in your temp repository.

**Comment by eugenk** [comment] 2015-11-26 11:48
I mean, for TPTP/SoftFOL we have `<Declarations>`, `<Symbols>`, `<Axioms>` and `<Theorems>` in the output while THF only has `<Theorems>`.

Oh and yes, I tried one of the files from the temp repository. It is re-uploaded for the second listing in my opening post.

**Comment by sternk** [comment] 2015-11-26 11:52
I see. I'll continue investigating.

**Comment by eugenk** [comment] 2015-11-26 12:00
I found a better example in the repository. I removed the `AST` and `Text` elements from the xml for better readability:

```
$ hets -o xml --full-signatures -a none -v2 -O /tmp/ +RTS -K1G -RTS --full-theories -A https://gist.githubusercontent.com/eugenk/95b5c14c29f761dac07e/raw/a810b4a3d6dd1851844814ebdf23a98b9199354f/NUM636-3.p.het
$ cat /tmp/NUM636-3.p.xml
<?xml version='1.0' ?>
<DGraph filename="/Users/eugen/Uni/Informatik/Masterarbeit/resources/THF-embedded-in-Het/NUM/NUM636-3.p.het" mime-type="text/het" libname="NUM6363p" dgnodes="1" dgedges="0" nextlinkid="0">
  <DGNode name="NUM6363" range="/Users/eugen/Uni/Informatik/Masterarbeit/resources/THF-embedded-in-Het/NUM/NUM636-3.p.het:3.1-3.14" reference="false" logic="THF" refname="NUM6363" relxpath="/">
    <Axioms>
      <Axiom name="one_is_first" range="/Users/eugen/Uni/Informatik/Masterarbeit/resources/THF-embedded-in-Het/NUM/NUM636-3.p.het:41.8-43.11">
      </Axiom>
      <Axiom name="succ_injective" range="/Users/eugen/Uni/Informatik/Masterarbeit/resources/THF-embedded-in-Het/NUM/NUM636-3.p.het:46.8-49.15">
      </Axiom>
      <Axiom name="induction" range="/Users/eugen/Uni/Informatik/Masterarbeit/resources/THF-embedded-in-Het/NUM/NUM636-3.p.het:52.8-58.17">
      </Axiom>
      <Axiom name="m_defn" range="/Users/eugen/Uni/Informatik/Masterarbeit/resources/THF-embedded-in-Het/NUM/NUM636-3.p.het:64.7-67.13">
      </Axiom>
      <Axiom name="m_is_one" range="/Users/eugen/Uni/Informatik/Masterarbeit/resources/THF-embedded-in-Het/NUM/NUM636-3.p.het:70.7-70.13">
      </Axiom>
      <Axiom name="m_is_next" range="/Users/eugen/Uni/Informatik/Masterarbeit/resources/THF-embedded-in-Het/NUM/NUM636-3.p.het:73.8-75.24">
      </Axiom>
    </Axioms>
    <Theorems>
      <Theorem status="open" name="m_is_all" range="/Users/eugen/Uni/Informatik/Masterarbeit/resources/THF-embedded-in-Het/NUM/NUM636-3.p.het:78.8-79.13">
      </Theorem>
    </Theorems>
  </DGNode>
</DGraph>
```

**Comment by sternk** [comment] 2015-11-26 12:03
Ok thanks. I now know why my first approach doesn't work. It will take a while to implement properly but I'll try to do it today

**Comment by tillmo** [comment] 2015-11-26 12:09
@eugenk, the commit cited above is a first fix for SoftFOL. The problem is that I do not get the types of the symbols - they are not stored in the sentences. I would need the signature, but currently, the signature is not passed to symsOfSen. Perhaps we could change this.

**Comment by sternk** [comment] 2015-11-26 12:11
Yes - that would be good! - Type inference won't work on a
sentence-by-sentence basis for THF either

**Comment by tillmo** [comment] 2015-11-26 12:19
OK, a7338b1 does this.

**Comment by sternk** [comment] 2015-11-26 13:04
Am I right in thinking that the list of symbols should not contain bound variables?

**Comment by eugenk** [comment] 2015-11-26 13:06
Correct. Those variables should not be in the list.

**Comment by tillmo** [comment] 2015-11-26 14:07
#1547 should fix the issue for SoftFOL

**Comment by tillmo** [comment] 2015-11-26 16:26
my commit message auto-closed this issue, but we also need it for THF...

**Comment by sternk** [comment] 2015-11-26 21:15
@eugenk can you check if 91673da does what you need?

**Comment by eugenk** [comment] 2015-11-26 21:33
It's better. The Axioms now have the Symbols. The XML output, however, still lacks the `<Declarations>` and `<Symbols>` items that should contain a list of the symbols as well (see the CASL output in the opening post). In Ontohub, we depend on the `<Symbols>` list to correlate to the `<Symbol>` inside each `<Axiom>` and `<Theorem>`.

**Comment by sternk** [comment] 2015-11-26 21:44
I have now added sym_of to THF and <Symbols> appears now as well. Is it ok that <Declarations> seems to have the same content?

**Comment by eugenk** [comment] 2015-11-26 22:06
It is working now. Thanks!

**Comment by sternk** [comment] 2015-11-26 22:07
Great!

**Closed by sternk** 2015-11-26 22:07 UTC
